coverage:
  status:
    patch:
      default:
        branches:
          - "!main"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "go/pkg/ent"
  - "**/*_mock.go"
  - "go/test"
  - "go/pkg/writer/mock"
  - "go/pkg/reader/mock"
