// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GooseDbVersionColumns holds the columns for the "goose_db_version" table.
	GooseDbVersionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "version_id", Type: field.TypeInt},
		{Name: "is_applied", Type: field.TypeBool},
		{Name: "tstamp", Type: field.TypeTime, Nullable: true},
	}
	// GooseDbVersionTable holds the schema information for the "goose_db_version" table.
	GooseDbVersionTable = &schema.Table{
		Name:       "goose_db_version",
		Columns:    GooseDbVersionColumns,
		PrimaryKey: []*schema.Column{GooseDbVersionColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "flags", Type: field.TypeInt},
		{Name: "last_logged_in_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GooseDbVersionTable,
		UsersTable,
	}
)

func init() {
	GooseDbVersionTable.Annotation = &entsql.Annotation{
		Table: "goose_db_version",
	}
}
