// Code generated by entc, DO NOT EDIT.

package coffeebean

const (
	// Label holds the string label denoting the coffeebean type in the database.
	Label = "coffee_bean"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFarmName holds the string denoting the farm_name field in the database.
	FieldFarmName = "farm_name"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldShopID holds the string denoting the shop_id field in the database.
	FieldShopID = "shop_id"
	// FieldRoastedDegree holds the string denoting the roasted_degree field in the database.
	FieldRoastedDegree = "roasted_degree"
	// FieldRoastedAt holds the string denoting the roasted_at field in the database.
	FieldRoastedAt = "roasted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the coffeebean in the database.
	Table = "coffee_beans"
)

// Columns holds all SQL columns for coffeebean fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldFarmName,
	FieldCountry,
	FieldShopID,
	FieldRoastedDegree,
	FieldRoastedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
