// Code generated by entc, DO NOT EDIT.

package coffeebean

const (
	// Label holds the string label denoting the coffeebean type in the database.
	Label = "coffee_bean"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFarmName holds the string denoting the farm_name field in the database.
	FieldFarmName = "farm_name"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldRoastDegree holds the string denoting the roast_degree field in the database.
	FieldRoastDegree = "roast_degree"
	// FieldRoastedAt holds the string denoting the roasted_at field in the database.
	FieldRoastedAt = "roasted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUsersCoffeeBeans holds the string denoting the users_coffee_beans edge name in mutations.
	EdgeUsersCoffeeBeans = "users_coffee_beans"
	// Table holds the table name of the coffeebean in the database.
	Table = "coffee_beans"
	// UsersCoffeeBeansTable is the table that holds the users_coffee_beans relation/edge.
	UsersCoffeeBeansTable = "users_coffee_beans"
	// UsersCoffeeBeansInverseTable is the table name for the UsersCoffeeBean entity.
	// It exists in this package in order to avoid circular dependency with the "userscoffeebean" package.
	UsersCoffeeBeansInverseTable = "users_coffee_beans"
	// UsersCoffeeBeansColumn is the table column denoting the users_coffee_beans relation/edge.
	UsersCoffeeBeansColumn = "coffee_bean_id"
)

// Columns holds all SQL columns for coffeebean fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldFarmName,
	FieldCountry,
	FieldRoastDegree,
	FieldRoastedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
