// Code generated by entc, DO NOT EDIT.

package goosedbversion

const (
	// Label holds the string label denoting the goosedbversion type in the database.
	Label = "goose_db_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersionID holds the string denoting the version_id field in the database.
	FieldVersionID = "version_id"
	// FieldIsApplied holds the string denoting the is_applied field in the database.
	FieldIsApplied = "is_applied"
	// FieldTstamp holds the string denoting the tstamp field in the database.
	FieldTstamp = "tstamp"
	// Table holds the table name of the goosedbversion in the database.
	Table = "goose_db_version"
)

// Columns holds all SQL columns for goosedbversion fields.
var Columns = []string{
	FieldID,
	FieldVersionID,
	FieldIsApplied,
	FieldTstamp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
