// Code generated by MockGen. DO NOT EDIT.
// Source: ./user_brew_recipe.go

// Package writer is a generated GoMock package.
package writer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/k3forx/coffee_memo/pkg/model"
	context "golang.org/x/net/context"
)

// MockUserBrewRecipe is a mock of UserBrewRecipe interface.
type MockUserBrewRecipe struct {
	ctrl     *gomock.Controller
	recorder *MockUserBrewRecipeMockRecorder
}

// MockUserBrewRecipeMockRecorder is the mock recorder for MockUserBrewRecipe.
type MockUserBrewRecipeMockRecorder struct {
	mock *MockUserBrewRecipe
}

// NewMockUserBrewRecipe creates a new mock instance.
func NewMockUserBrewRecipe(ctrl *gomock.Controller) *MockUserBrewRecipe {
	mock := &MockUserBrewRecipe{ctrl: ctrl}
	mock.recorder = &MockUserBrewRecipeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserBrewRecipe) EXPECT() *MockUserBrewRecipeMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserBrewRecipe) Create(ctx context.Context, userBrewRecipe *model.UserBrewRecipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userBrewRecipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserBrewRecipeMockRecorder) Create(ctx, userBrewRecipe interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserBrewRecipe)(nil).Create), ctx, userBrewRecipe)
}
