// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k3forx/coffee_memo/pkg/ent/predicate"
	"github.com/k3forx/coffee_memo/pkg/ent/userbrewrecipe"
)

// UserBrewRecipeDelete is the builder for deleting a UserBrewRecipe entity.
type UserBrewRecipeDelete struct {
	config
	hooks    []Hook
	mutation *UserBrewRecipeMutation
}

// Where appends a list predicates to the UserBrewRecipeDelete builder.
func (ubrd *UserBrewRecipeDelete) Where(ps ...predicate.UserBrewRecipe) *UserBrewRecipeDelete {
	ubrd.mutation.Where(ps...)
	return ubrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ubrd *UserBrewRecipeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ubrd.hooks) == 0 {
		affected, err = ubrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserBrewRecipeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ubrd.mutation = mutation
			affected, err = ubrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ubrd.hooks) - 1; i >= 0; i-- {
			if ubrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ubrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ubrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ubrd *UserBrewRecipeDelete) ExecX(ctx context.Context) int {
	n, err := ubrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ubrd *UserBrewRecipeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userbrewrecipe.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: userbrewrecipe.FieldID,
			},
		},
	}
	if ps := ubrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ubrd.driver, _spec)
}

// UserBrewRecipeDeleteOne is the builder for deleting a single UserBrewRecipe entity.
type UserBrewRecipeDeleteOne struct {
	ubrd *UserBrewRecipeDelete
}

// Exec executes the deletion query.
func (ubrdo *UserBrewRecipeDeleteOne) Exec(ctx context.Context) error {
	n, err := ubrdo.ubrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userbrewrecipe.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ubrdo *UserBrewRecipeDeleteOne) ExecX(ctx context.Context) {
	ubrdo.ubrd.ExecX(ctx)
}
