// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k3forx/coffee_memo/pkg/ent/predicate"
	"github.com/k3forx/coffee_memo/pkg/ent/user"
	"github.com/k3forx/coffee_memo/pkg/ent/usercoffeebean"
	"github.com/k3forx/coffee_memo/pkg/ent/userdriprecipe"
)

// UserDripRecipeQuery is the builder for querying UserDripRecipe entities.
type UserDripRecipeQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserDripRecipe
	// eager-loading edges.
	withUserCoffeeBean *UserCoffeeBeanQuery
	withUser           *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserDripRecipeQuery builder.
func (udrq *UserDripRecipeQuery) Where(ps ...predicate.UserDripRecipe) *UserDripRecipeQuery {
	udrq.predicates = append(udrq.predicates, ps...)
	return udrq
}

// Limit adds a limit step to the query.
func (udrq *UserDripRecipeQuery) Limit(limit int) *UserDripRecipeQuery {
	udrq.limit = &limit
	return udrq
}

// Offset adds an offset step to the query.
func (udrq *UserDripRecipeQuery) Offset(offset int) *UserDripRecipeQuery {
	udrq.offset = &offset
	return udrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (udrq *UserDripRecipeQuery) Unique(unique bool) *UserDripRecipeQuery {
	udrq.unique = &unique
	return udrq
}

// Order adds an order step to the query.
func (udrq *UserDripRecipeQuery) Order(o ...OrderFunc) *UserDripRecipeQuery {
	udrq.order = append(udrq.order, o...)
	return udrq
}

// QueryUserCoffeeBean chains the current query on the "user_coffee_bean" edge.
func (udrq *UserDripRecipeQuery) QueryUserCoffeeBean() *UserCoffeeBeanQuery {
	query := &UserCoffeeBeanQuery{config: udrq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := udrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := udrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userdriprecipe.Table, userdriprecipe.FieldID, selector),
			sqlgraph.To(usercoffeebean.Table, usercoffeebean.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userdriprecipe.UserCoffeeBeanTable, userdriprecipe.UserCoffeeBeanColumn),
		)
		fromU = sqlgraph.SetNeighbors(udrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (udrq *UserDripRecipeQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: udrq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := udrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := udrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userdriprecipe.Table, userdriprecipe.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userdriprecipe.UserTable, userdriprecipe.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(udrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserDripRecipe entity from the query.
// Returns a *NotFoundError when no UserDripRecipe was found.
func (udrq *UserDripRecipeQuery) First(ctx context.Context) (*UserDripRecipe, error) {
	nodes, err := udrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userdriprecipe.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) FirstX(ctx context.Context) *UserDripRecipe {
	node, err := udrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserDripRecipe ID from the query.
// Returns a *NotFoundError when no UserDripRecipe ID was found.
func (udrq *UserDripRecipeQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = udrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userdriprecipe.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) FirstIDX(ctx context.Context) int32 {
	id, err := udrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserDripRecipe entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserDripRecipe entity is found.
// Returns a *NotFoundError when no UserDripRecipe entities are found.
func (udrq *UserDripRecipeQuery) Only(ctx context.Context) (*UserDripRecipe, error) {
	nodes, err := udrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userdriprecipe.Label}
	default:
		return nil, &NotSingularError{userdriprecipe.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) OnlyX(ctx context.Context) *UserDripRecipe {
	node, err := udrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserDripRecipe ID in the query.
// Returns a *NotSingularError when more than one UserDripRecipe ID is found.
// Returns a *NotFoundError when no entities are found.
func (udrq *UserDripRecipeQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = udrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userdriprecipe.Label}
	default:
		err = &NotSingularError{userdriprecipe.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := udrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserDripRecipes.
func (udrq *UserDripRecipeQuery) All(ctx context.Context) ([]*UserDripRecipe, error) {
	if err := udrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return udrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) AllX(ctx context.Context) []*UserDripRecipe {
	nodes, err := udrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserDripRecipe IDs.
func (udrq *UserDripRecipeQuery) IDs(ctx context.Context) ([]int32, error) {
	var ids []int32
	if err := udrq.Select(userdriprecipe.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) IDsX(ctx context.Context) []int32 {
	ids, err := udrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (udrq *UserDripRecipeQuery) Count(ctx context.Context) (int, error) {
	if err := udrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return udrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) CountX(ctx context.Context) int {
	count, err := udrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (udrq *UserDripRecipeQuery) Exist(ctx context.Context) (bool, error) {
	if err := udrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return udrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (udrq *UserDripRecipeQuery) ExistX(ctx context.Context) bool {
	exist, err := udrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserDripRecipeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (udrq *UserDripRecipeQuery) Clone() *UserDripRecipeQuery {
	if udrq == nil {
		return nil
	}
	return &UserDripRecipeQuery{
		config:             udrq.config,
		limit:              udrq.limit,
		offset:             udrq.offset,
		order:              append([]OrderFunc{}, udrq.order...),
		predicates:         append([]predicate.UserDripRecipe{}, udrq.predicates...),
		withUserCoffeeBean: udrq.withUserCoffeeBean.Clone(),
		withUser:           udrq.withUser.Clone(),
		// clone intermediate query.
		sql:    udrq.sql.Clone(),
		path:   udrq.path,
		unique: udrq.unique,
	}
}

// WithUserCoffeeBean tells the query-builder to eager-load the nodes that are connected to
// the "user_coffee_bean" edge. The optional arguments are used to configure the query builder of the edge.
func (udrq *UserDripRecipeQuery) WithUserCoffeeBean(opts ...func(*UserCoffeeBeanQuery)) *UserDripRecipeQuery {
	query := &UserCoffeeBeanQuery{config: udrq.config}
	for _, opt := range opts {
		opt(query)
	}
	udrq.withUserCoffeeBean = query
	return udrq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (udrq *UserDripRecipeQuery) WithUser(opts ...func(*UserQuery)) *UserDripRecipeQuery {
	query := &UserQuery{config: udrq.config}
	for _, opt := range opts {
		opt(query)
	}
	udrq.withUser = query
	return udrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int32 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserDripRecipe.Query().
//		GroupBy(userdriprecipe.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (udrq *UserDripRecipeQuery) GroupBy(field string, fields ...string) *UserDripRecipeGroupBy {
	grbuild := &UserDripRecipeGroupBy{config: udrq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := udrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return udrq.sqlQuery(ctx), nil
	}
	grbuild.label = userdriprecipe.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int32 `json:"user_id,omitempty"`
//	}
//
//	client.UserDripRecipe.Query().
//		Select(userdriprecipe.FieldUserID).
//		Scan(ctx, &v)
//
func (udrq *UserDripRecipeQuery) Select(fields ...string) *UserDripRecipeSelect {
	udrq.fields = append(udrq.fields, fields...)
	selbuild := &UserDripRecipeSelect{UserDripRecipeQuery: udrq}
	selbuild.label = userdriprecipe.Label
	selbuild.flds, selbuild.scan = &udrq.fields, selbuild.Scan
	return selbuild
}

func (udrq *UserDripRecipeQuery) prepareQuery(ctx context.Context) error {
	for _, f := range udrq.fields {
		if !userdriprecipe.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if udrq.path != nil {
		prev, err := udrq.path(ctx)
		if err != nil {
			return err
		}
		udrq.sql = prev
	}
	return nil
}

func (udrq *UserDripRecipeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserDripRecipe, error) {
	var (
		nodes       = []*UserDripRecipe{}
		_spec       = udrq.querySpec()
		loadedTypes = [2]bool{
			udrq.withUserCoffeeBean != nil,
			udrq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*UserDripRecipe).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &UserDripRecipe{config: udrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, udrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := udrq.withUserCoffeeBean; query != nil {
		ids := make([]int32, 0, len(nodes))
		nodeids := make(map[int32][]*UserDripRecipe)
		for i := range nodes {
			fk := nodes[i].CoffeeBeanID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(usercoffeebean.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "coffee_bean_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.UserCoffeeBean = n
			}
		}
	}

	if query := udrq.withUser; query != nil {
		ids := make([]int32, 0, len(nodes))
		nodeids := make(map[int32][]*UserDripRecipe)
		for i := range nodes {
			fk := nodes[i].UserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	return nodes, nil
}

func (udrq *UserDripRecipeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := udrq.querySpec()
	_spec.Node.Columns = udrq.fields
	if len(udrq.fields) > 0 {
		_spec.Unique = udrq.unique != nil && *udrq.unique
	}
	return sqlgraph.CountNodes(ctx, udrq.driver, _spec)
}

func (udrq *UserDripRecipeQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := udrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (udrq *UserDripRecipeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userdriprecipe.Table,
			Columns: userdriprecipe.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: userdriprecipe.FieldID,
			},
		},
		From:   udrq.sql,
		Unique: true,
	}
	if unique := udrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := udrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userdriprecipe.FieldID)
		for i := range fields {
			if fields[i] != userdriprecipe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := udrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := udrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := udrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := udrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (udrq *UserDripRecipeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(udrq.driver.Dialect())
	t1 := builder.Table(userdriprecipe.Table)
	columns := udrq.fields
	if len(columns) == 0 {
		columns = userdriprecipe.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if udrq.sql != nil {
		selector = udrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if udrq.unique != nil && *udrq.unique {
		selector.Distinct()
	}
	for _, p := range udrq.predicates {
		p(selector)
	}
	for _, p := range udrq.order {
		p(selector)
	}
	if offset := udrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := udrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserDripRecipeGroupBy is the group-by builder for UserDripRecipe entities.
type UserDripRecipeGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (udrgb *UserDripRecipeGroupBy) Aggregate(fns ...AggregateFunc) *UserDripRecipeGroupBy {
	udrgb.fns = append(udrgb.fns, fns...)
	return udrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (udrgb *UserDripRecipeGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := udrgb.path(ctx)
	if err != nil {
		return err
	}
	udrgb.sql = query
	return udrgb.sqlScan(ctx, v)
}

func (udrgb *UserDripRecipeGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range udrgb.fields {
		if !userdriprecipe.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := udrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := udrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (udrgb *UserDripRecipeGroupBy) sqlQuery() *sql.Selector {
	selector := udrgb.sql.Select()
	aggregation := make([]string, 0, len(udrgb.fns))
	for _, fn := range udrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(udrgb.fields)+len(udrgb.fns))
		for _, f := range udrgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(udrgb.fields...)...)
}

// UserDripRecipeSelect is the builder for selecting fields of UserDripRecipe entities.
type UserDripRecipeSelect struct {
	*UserDripRecipeQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (udrs *UserDripRecipeSelect) Scan(ctx context.Context, v interface{}) error {
	if err := udrs.prepareQuery(ctx); err != nil {
		return err
	}
	udrs.sql = udrs.UserDripRecipeQuery.sqlQuery(ctx)
	return udrs.sqlScan(ctx, v)
}

func (udrs *UserDripRecipeSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := udrs.sql.Query()
	if err := udrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
