// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k3forx/coffee_memo/pkg/ent/predicate"
	"github.com/k3forx/coffee_memo/pkg/ent/usercoffeebean"
)

// UserCoffeeBeanDelete is the builder for deleting a UserCoffeeBean entity.
type UserCoffeeBeanDelete struct {
	config
	hooks    []Hook
	mutation *UserCoffeeBeanMutation
}

// Where appends a list predicates to the UserCoffeeBeanDelete builder.
func (ucbd *UserCoffeeBeanDelete) Where(ps ...predicate.UserCoffeeBean) *UserCoffeeBeanDelete {
	ucbd.mutation.Where(ps...)
	return ucbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ucbd *UserCoffeeBeanDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ucbd.hooks) == 0 {
		affected, err = ucbd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserCoffeeBeanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ucbd.mutation = mutation
			affected, err = ucbd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ucbd.hooks) - 1; i >= 0; i-- {
			if ucbd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ucbd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ucbd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucbd *UserCoffeeBeanDelete) ExecX(ctx context.Context) int {
	n, err := ucbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ucbd *UserCoffeeBeanDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: usercoffeebean.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: usercoffeebean.FieldID,
			},
		},
	}
	if ps := ucbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ucbd.driver, _spec)
}

// UserCoffeeBeanDeleteOne is the builder for deleting a single UserCoffeeBean entity.
type UserCoffeeBeanDeleteOne struct {
	ucbd *UserCoffeeBeanDelete
}

// Exec executes the deletion query.
func (ucbdo *UserCoffeeBeanDeleteOne) Exec(ctx context.Context) error {
	n, err := ucbdo.ucbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usercoffeebean.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ucbdo *UserCoffeeBeanDeleteOne) ExecX(ctx context.Context) {
	ucbdo.ucbd.ExecX(ctx)
}
