// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k3forx/coffee_memo/pkg/ent/predicate"
	"github.com/k3forx/coffee_memo/pkg/ent/userdriprecipe"
)

// UserDripRecipeDelete is the builder for deleting a UserDripRecipe entity.
type UserDripRecipeDelete struct {
	config
	hooks    []Hook
	mutation *UserDripRecipeMutation
}

// Where appends a list predicates to the UserDripRecipeDelete builder.
func (udrd *UserDripRecipeDelete) Where(ps ...predicate.UserDripRecipe) *UserDripRecipeDelete {
	udrd.mutation.Where(ps...)
	return udrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (udrd *UserDripRecipeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(udrd.hooks) == 0 {
		affected, err = udrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserDripRecipeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			udrd.mutation = mutation
			affected, err = udrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(udrd.hooks) - 1; i >= 0; i-- {
			if udrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = udrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, udrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (udrd *UserDripRecipeDelete) ExecX(ctx context.Context) int {
	n, err := udrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (udrd *UserDripRecipeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userdriprecipe.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt32,
				Column: userdriprecipe.FieldID,
			},
		},
	}
	if ps := udrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, udrd.driver, _spec)
}

// UserDripRecipeDeleteOne is the builder for deleting a single UserDripRecipe entity.
type UserDripRecipeDeleteOne struct {
	udrd *UserDripRecipeDelete
}

// Exec executes the deletion query.
func (udrdo *UserDripRecipeDeleteOne) Exec(ctx context.Context) error {
	n, err := udrdo.udrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userdriprecipe.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (udrdo *UserDripRecipeDeleteOne) ExecX(ctx context.Context) {
	udrdo.udrd.ExecX(ctx)
}
