linters-settings:
  custom:
    jsonCameler:
      path: ../plugins/jsonCameler.so
      description: Check whether JSON tags are written in lowerCamelCase
      original-url: github.com/k3forx/jsonCameler

linters:
  enable:
    - jsonCameler
