// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GooseDbVersion is the predicate function for goosedbversion builders.
type GooseDbVersion func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserCoffeeBean is the predicate function for usercoffeebean builders.
type UserCoffeeBean func(*sql.Selector)
