// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type CoffeeShop struct {
	ent.Schema
}

func (CoffeeShop) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.String("name"), field.String("shop_url").Optional(), field.Time("open_time").Optional(), field.Time("close_time").Optional(), field.Time("created_at"), field.Time("updated_at"), field.Time("closed_at").Optional()}
}
func (CoffeeShop) Edges() []ent.Edge {
	return nil
}
func (CoffeeShop) Annotations() []schema.Annotation {
	return nil
}
