// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type GooseDbVersion struct {
	ent.Schema
}

func (GooseDbVersion) Fields() []ent.Field {
	return []ent.Field{field.Uint64("id").Unique(), field.Int("version_id"), field.Bool("is_applied"), field.Time("tstamp").Optional()}
}
func (GooseDbVersion) Edges() []ent.Edge {
	return nil
}
func (GooseDbVersion) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "goose_db_version"}}
}
