// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type UserBrewRecipe struct {
	ent.Schema
}

func (UserBrewRecipe) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.Int32("status"), field.Int32("user_id").Optional(), field.Int32("user_coffee_bean_id").Optional(), field.Float("coffee_bean_weight"), field.String("coffee_bean_grind"), field.Float("liquid_weight"), field.Float("temperature"), field.String("step_one"), field.String("step_two"), field.String("step_three"), field.String("step_four"), field.String("step_five"), field.String("memo").Optional(), field.Time("created_at"), field.Time("updated_at"), field.Time("deleted_at").Optional()}
}
func (UserBrewRecipe) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user_coffee_bean", UserCoffeeBean.Type).Ref("user_brew_recipes").Unique().Field("user_coffee_bean_id"), edge.From("user", User.Type).Ref("user_brew_recipes").Unique().Field("user_id")}
}
func (UserBrewRecipe) Annotations() []schema.Annotation {
	return nil
}
