name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # golangci-lint:
  #   name: golangci-lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
  #         version: v1.45
  #         args: --timeout=10m

  #         # Optional: working directory, useful for monorepos
  #         working-directory: ./go

  custom-linters:
    name: custom-linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: run
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN  }}
        run: |
          export GOSUMDB=off
          sed -e "s/your_github_username/k3forx/" -e "s/your_github_access_token/${REPO_ACCESS_TOKEN}/" ./.netrc.example > ~/.netrc
          go install github.com/k3forx/todoAuthor/cmd/todoAuthor@latest
          cd ./go
          go vet -vettool=`which todoAuthor` ./...
