name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # golangci-lint:
  #   name: golangci-lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
  #         version: v1.45
  #         args: --timeout=10m

  #         # Optional: working directory, useful for monorepos
  #         working-directory: ./go

  custom:
    name: custom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: |
          cd ./go
          pwd
          go version
          go install github.com/k3forx/jsonCameler/cmd/jsonCameler@latest
          which jsonCameler
          go vet -vettool=`which jsonCameler` ./...
